"""add importance_score to messages

Revision ID: bb722cb60c5f
Revises: 092aecec859f
Create Date: 2026-09-03 02:20:04.843341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb722cb60c5f'
down_revision: Union[str, Sequence[str], None] = '092aecec859f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('importance_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'importance_score')
    # ### end Alembic commands ###
